// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzKgdhj7hzbb_BQ1JjlS2pkHM5Z5Kd0o8',
    appId: '1:35853685399:web:9daf5f56ac581e7a870fd2',
    messagingSenderId: '35853685399',
    projectId: 'workzen2025',
    authDomain: 'workzen2025.firebaseapp.com',
    storageBucket: 'workzen2025.firebasestorage.app',
    measurementId: 'G-4JKEN0SR06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPWzMjMkrz9MMD4fgbYDa7aEWrjcLuz1s',
    appId: '1:35853685399:android:f3b9b85fc78a46b0870fd2',
    messagingSenderId: '35853685399',
    projectId: 'workzen2025',
    storageBucket: 'workzen2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0rKKJAbPrSu5LF5EdW0tZvZE8Qww6As',
    appId: '1:35853685399:ios:2f5304857df5cb79870fd2',
    messagingSenderId: '35853685399',
    projectId: 'workzen2025',
    storageBucket: 'workzen2025.firebasestorage.app',
    iosBundleId: 'com.example.workzen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0rKKJAbPrSu5LF5EdW0tZvZE8Qww6As',
    appId: '1:35853685399:ios:2f5304857df5cb79870fd2',
    messagingSenderId: '35853685399',
    projectId: 'workzen2025',
    storageBucket: 'workzen2025.firebasestorage.app',
    iosBundleId: 'com.example.workzen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzKgdhj7hzbb_BQ1JjlS2pkHM5Z5Kd0o8',
    appId: '1:35853685399:web:a7b64b430e25ded2870fd2',
    messagingSenderId: '35853685399',
    projectId: 'workzen2025',
    authDomain: 'workzen2025.firebaseapp.com',
    storageBucket: 'workzen2025.firebasestorage.app',
    measurementId: 'G-RM5QZZDVTT',
  );

}